version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env.local
    command: ["pnpm", "start", "-H", "0.0.0.0"]
    restart: unless-stopped
