FROM node:20-alpine AS base
ARG BUILD_FOLDER=""
ENV DOCKER_BUILD_FOLDER=${BUILD_FOLDER}
ARG INSTALL_PATH=/app

FROM base AS deps
RUN apk add --no-cache libc6-compat bash vim busybox-extras
WORKDIR /app
ARG CICD_PUBLISH_TOKEN

ENV http_proxy=${http_proxy}
ENV https_proxy=${http_proxy}
ENV HTTP_PROXY=${http_proxy}
ENV HTTPS_PROXY=${http_proxy}

RUN npm install -g pnpm@10.2.0
RUN npm config set proxy ${http_proxy}
RUN npm config set https-proxy ${https_proxy}

COPY ${DOCKER_BUILD_FOLDER}package.json ${DOCKER_BUILD_FOLDER}pnpm-lock.yaml* ${DOCKER_BUILD_FOLDER}.npmrc* ./
RUN pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ${DOCKER_BUILD_FOLDER}. .

ARG CICD_PUBLISH_TOKEN
ENV NEXT_TELEMETRY_DISABLED=1
ENV http_proxy=${http_proxy}
ENV https_proxy=${http_proxy}
ENV HTTP_PROXY=${http_proxy}
ENV HTTPS_PROXY=${http_proxy}

RUN npm install -g pnpm@10.2.0
RUN pnpm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# If your app needs the public folder
COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Optional: copy .env files if you rely on them at runtime via file reading
# It's usually better to provide env vars via Kubernetes ConfigMap/Secret
COPY --from=builder --chown=nextjs:nodejs /app/.env* ./

USER nextjs

EXPOSE 3002
ENV PORT=3002
ENV HOSTNAME="0.0.0.0"

# Next.js standalone runner
CMD ["node", "server.js"]
